### ISSUE TITLE
Handle screen resizing

### ISSUE THREAD

**Issue by raboof** [Immington-Industries/way-cooler-bg#2]
At first glance, it seems (at least under wlc-x11) way-cooler-bg decides the size of the background once upon startup, and after that doesn't respond to screen size changes.

(I'm quite unfamiliar with way-cooler / way-cooler-bg / wayland, so I might be reporting to the wrong project here - bear with me :) )

**Comment by Timidger** [comment]
That is correct, the Way Cooler background program is currently very, very basic. Even if Way Cooler supported multi-head output (which it doesn't currently, which is something I'm going to address soon), the background program wouldn't even handle that correctly.

The way the background is implemented Way Cooler is side is quite a hack as well. To do it properly, Way Cooler should implement a proper Wayland protocol (either similar to or exactly how [sway implements it](https://github.com/SirCmpwn/sway/blob/master/protocols/desktop-shell.xml#L10)). Right now, the background program is "special" because it uses a special class name that Way Cooler looks for, instead of having the surface passed directly to Way Cooler. This is something I plan to fix in the future, once we have other, more important features in place (such as a bar). The nice thing about the protocols though is that once we implement a standard one, any programs that use that protocol (eg, sway-bg) automatically works for free with Way Cooler (so it would be possible to swap out `way-cooler-bg` with a program that has more features, if the user wanted).

Despite all that, it's (very) possible right now to handle resizing the background when the output size changes. I've added a ticket on Way Cooler side (because that's where it would have to be changed) to implement this feature, which should be in 0.4.2.

Also, side note -- very soon we will begin releasing github releases of Way Cooler that will be tarred versions of `way-cooler`, `way-cooler-bg`, and an install script to put them in their proper place. So soon it will no longer be necessary for users to follow the insane steps needed to compile Way Cooler and the way-cooler-bg from source, they can just get the binaries directly from us. Thanks again for your README contributions though! 👍
